openapi: 3.0.0
info:
  title: E-Rezept API
  version: 1.0.0
servers:
  - url: http://{{address_fachdienst}}
tags:
  - name: Rezept abrufen
  - name: Rezept zurückgeben
  - name: Rezept löschen
  - name: Quittung abrufen
  - name: Quittung erneut abrufen
paths:
  /Task/$create:
    post:
      tags:
        - Rezept abrufen
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateTask'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTask'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/fhir+xml
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token_arztpraxis}}
      responses:
        '201':
          description: Successful response
          content:
            application/json: {}
  /Task/{task_id}/$activate:
      post:
        tags:
          - Rezept abrufen
        requestBody:
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ActivateTask'
            application/json:
              schema:
                $ref: '#/components/schemas/ActivateTask'
        parameters:
          - name: X-AccessCode
            in: header
            schema:
              type: string
            example: '{{task_access_code}}'
          - name: Authorization
            in: header
            schema:
              type: string
            example: Bearer {{access_token_arztpraxis}}
          - name: task_id
            in: path
            schema:
              type: string
            required: true
        responses:
          '200':
            description: Successful response
  /Task/{task_id}/$accept:
    post:
      tags:
        - Rezept abrufen
      parameters:
        - name: Accept
          in: header
          schema:
            type: number
          example: application/fhir+xml;q=1.0, application/json+fhir;q=0.9
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token_apotheke}}
        - name: x-accesscode
          in: header
          schema:
            type: string
          example: 418af289f80ca1f7189cff6dc43cbf302224f543f13a7c0b479f8042777c67ec
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/fhir+xml
        - name: Accept-Charset
          in: header
          schema:
            type: string
          example: utf-8
        - name: ac
          in: query
          schema:
            type: string
          example: '{{task_access_code}}'
        - name: task_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response

  /Task/{task_id}/$reject:
    post:
      tags:
        - Rezept zurückgeben
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/fhir+xml
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token_apotheke}}
        - name: secret
          in: query
          schema:
            type: string
          example: '{{task_secret}}'
        - name: task_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Successful response
  /Task/{task_id}/$abort:
    post:
      tags:
        - Rezept löschen
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/fhir+xml
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token_arztpraxis}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/fhir+xml; charset=UTF-8
        - name: X-AccessCode
          in: header
          schema:
            type: string
          example: '{{task_access_code}}'
        - name: task_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Successful response
  /Task/{task_id}/$close:
    post:
      tags:
        - Quittung abrufen
      requestBody:
        content:
          application/xml:
              schema:
                $ref: '#/components/schemas/MedicationDispense'
          application/json:
              schema:
                $ref: '#/components/schemas/MedicationDispense'
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/fhir+xml
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token_apotheke}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/fhir+xml; charset=UTF-8
        - name: secret
          in: query
          schema:
            type: string
          example: '{{task_secret}}'
        - name: task_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
  /Task/{task_id}:
    get:
      tags:
        - Quittung erneut abrufen
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{access_token_patient}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/fhir+json; charset=UTF-8
        - name: X-Api-Key
          in: header
          schema:
            type: string
          example: DEpsSHb/5DKJwV3TjhZQXw==
        - name: Accept
          in: header
          schema:
            type: string
          example: application/fhir+json
        - name: task_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response

components:
  schemas:
    CreateTask:
      type: object
      xml:
        name: Parameters
        namespace: "http://hl7.org/fhir"
      properties:
        parameter:
          properties:
            name:
              properties:
                value:
                  example: "workflowType"
                  xml:
                    attribute: true
                    wrapped: true
            valueCoding:
              properties:
                system:
                  properties:
                     value:
                      example: "https://gematik.de/fhir/erp/CodeSystem/GEM_ERP_CS_FlowType"
                      xml:
                        attribute: true
                        wrapped: true
                code:
                  properties:
                      value:
                        example: "160"
                        xml:
                          attribute: true
                          wrapped: true
    ActivateTask:
      type: object
      xml:
        name: Parameters
        namespace: "http://hl7.org/fhir"
      properties:
        parameter:
          properties:
            name:
              properties:
                value:
                  example: "ePrescription"
                  xml:
                    attribute: true
                    wrapped: true
            resource:
              properties:
                Binary:
                  properties:
                    contentType:
                      properties:
                        value:
                          example: "application/pkcs7-mime"
                          xml:
                            attribute: true
                            wrapped: true
                    data:
                      properties:
                          value:
                            example: "{{signed_document}}"
                            xml:
                              attribute: true
                              wrapped: true
    MedicationDispense:
      type: object
      xml:
        name: MedicationDispense
        namespace: "http://hl7.org/fhir"
      properties:
        meta:
          properties:
            profile:
              properties:
                value:
                  example: "https://gematik.de/fhir/erp/StructureDefinition/GEM_ERP_PR_MedicationDispense"
                  xml:
                    attribute: true
                    wrapped: true
        contained:
          type: string
          example: '{{aps_medication}}'
        identifier:
          properties:
            system:
              properties:
                value:
                  example: "https://gematik.de/fhir/erp/NamingSystem/GEM_ERP_NS_PrescriptionId"
                  xml:
                    attribute: true
                    wrapped: true
            value:
              properties:
                value:
                  example: '{{aps_prescription_id}}'
                  xml:
                    attribute: true
                    wrapped: true
        status:
          properties:
            value:
              example: "completed"
              xml:
                attribute: true
                wrapped: true
        medicationReference:
          properties:
            reference:
              properties:
                value:
                  example: "#{{aps_medication_id}}"
                  xml:
                    attribute: true
                    wrapped: true
            display:
              properties:
                value:
                  example: "Sumatriptan-1a Pharma 100 mg Tabletten"
                  xml:
                    attribute: true
                    wrapped: true
        subject:
          properties:
            identifier:
              properties:
                system:
                  properties:
                    value:
                      example: "http://fhir.de/sid/gkv/kvid-10"
                      xml:
                        attribute: true
                        wrapped: true
                value:
                  properties:
                    value:
                      example: "{{kvnr}}"
                      xml:
                        attribute: true
                        wrapped: true
        performer:
          properties:
            actor:
              properties:
                identifier:
                  properties:
                    system:
                      properties:
                        value:
                          example: "https://gematik.de/fhir/sid/telematik-id"
                          xml:
                            attribute: true
                            wrapped: true
                    value:
                      properties:
                        value:
                          example: "{{aps_telematik_id}}"
                          xml:
                            attribute: true
                            wrapped: true
        whenHandedOver:
          properties:
            value:
              example: "2022-08-11T17:11:00+02:00"
              xml:
                attribute: true
                wrapped: true
        dosageInstruction:
          properties:
            text:
              properties:
                value:
                  example: "1-0-1-0"
                  xml:
                    attribute: true
                    wrapped: true

