name: Build with replacing includes


on:

  push:
    paths:
      -  resources/docs/*
    branches:
      - '**'


jobs:

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer --pre

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Reduce docs
        run: for filename in $(find resources/docs -name '*.adoc'); do newFileName=${filename//-source/} asciidoctor-reducer -o docs/$newFileName $filename done

      - name: Commit readme
        uses: EndBug/add-and-commit@v8