name: Build with replacing includes


on:

  push:
    paths:
      -  docs/architecture.adoc
    branches:
      - '**'


jobs:

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer --pre

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Reduce readme
        run: asciidoctor-reducer -o docs/architecture.adoc resources/docs/architecture-source.adoc

      - name: Commit readme
        uses: EndBug/add-and-commit@v8